# Makefile for CPE464 tcp and udp test code
# updated by Hugh Smith - April 2023

# all target makes UDP test code
# tcpAll target makes the TCP test code


CC= gcc
CFLAGS= -Wall -g -O0 
LIBS = 

OBJS = networks.o gethostbyname.o pollLib.o safeUtil.o printBuf.o sendData.o

# Uncomment next two lines if your using sendtoErr() library
LIBS += libcpe464.2.21.a -lstdc++ -ldl

ifeq ($(DEBUG), 1)
	DEBUG_FLAG = -DDEBUG
endif

CFLAGS += -D__LIBCPE464_ $(DEBUG_FLAG)

all: udpAll

udpAll: rcopy server

rcopy: rcopy.c $(OBJS) 
	$(CC) $(CFLAGS) -o rcopy rcopy.c $(OBJS) $(LIBS)

server: server.c $(OBJS) 
	$(CC) $(CFLAGS) -o server server.c  $(OBJS) $(LIBS)

.c.o:
	gcc -c $(CFLAGS) $< -o $@ $(LIBS)

debug:
	$(MAKE) clean
	$(MAKE) DEBUG=1 all

cleano:
	rm -f *.o

clean:
	rm -f rcopy server *.o




